image: "gcc:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build:
  stage: build
  before_script:
    - apt-get update -qq -y --no-install-recommends && apt-get install -y -qq cmake qtbase5-dev qtdeclarative5-dev ninja-build
    - mkdir build
  script:
    - cd build && cmake -G Ninja .. && ninja
