image: "gcc:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
- apt-get update -qq -y --no-install-recommends && apt-get install -y -qq cmake qtbase5-dev qtdeclarative5-dev
- mkdir build

stages:
- build

build:
    stage: build
    script:
    - cd build && cmake .. && make
